### ISSUE TITLE
Package dependencies not explicitly referenced in DESCRIPTION and R/ files

### ISSUE THREAD

**Issue by frankfarach** [michaelpawlus/irs990lookup#1]
When I forked and cloned this repo, loaded the package, and attempted to run `get_990_data()`, R did not know where to find `str_detect`, which is the first function referenced from an external package in `R/irs990_lookup.R`. Per [best practices](http://r-pkgs.had.co.nz/description.html#dependencies), such functions should be explicitly imported by a declaration in the DESCRIPTION file and explicitly called via `<package>::<fn>` in local package functions. I will submit a PR to fix these issues shortly.

**Comment by michaelpawlus** [comment]
Thanks for making these changes and for the that link to best practices. I had some concerns about the packages used and also wondered about how to note that there are dependent packages as I have seen elsewhere in R. This is really helpful. I merged your pull request. Thanks again.
